sudo: false
language: node_js
node_js:
- v7
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
after_success: npm run coverage
